= OpenJML-Wrapped Chaincode-As-A-Service Test Network Configuration
2023-06-25
:toc:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:cc-pkg-dir: chaincode-package/
:cc-name: tpcc

== WHAT IS WHAT

.Subdirectories & Files
* link:{cc-pkg-dir}/[`chaincode-package/`]: contains (with instructions to regenerate) a `{cc-name}.tgz` chaincode package, ready to install on Fabric peers (as external Chaincode-As-A-Service)
* link:fabric-config/[`fabric-config/`]: has been generated by `fablo`; you probably do not need to worry about anything here
* link:fabric-docker/[`fabric-docker/`]: has been generated by `fablo`; some files have been modified to support installing chaincode as an external servicefootnote:[Namely, the `commands-generated.sh` file has a custom function for this purpose]
* link:fabric-docker.sh[`fabric-docker.sh`]: script generated by `fablo` to manage the test network; refer to `$ ./fabric-docker.sh help` on how to use the script

Some subdirectories have their own _README_ files where you can learn more.


== HOW TO TRY IT OUT

.Prerequisites
Make sure you have `docker` available (with `compose`, of course)

.Instructions
. Ensure that the result of the link:{cc-pkg-dir}/scripts/calculate_package_id[`calculate_package_id`] script in link:{cc-pkg-dir}/[`chaincode-package/`] matches the one specified in link:fabric-docker/docker-compose.yaml[`fabric-docker/docker-compose.yaml`] and in link:fabric-docker/commands-generated.sh[`fabric-docker/commands-generated.sh`]; fix if necessary
. Start the `fablo` test network by issuing `$ ./fabric-docker.sh reset` (you can also use `up` if this is the first time)
. *Only if you had to change the package IDs for some reason:* Copy the chaincode package from link:{cc-pkg-dir}/[`{cc-pkg-dir}/`] to link:fabric-config/chaincode-packages/[`fabric-config/chaincode-packages/`] using the link:{cc-pkg-dir}/scripts/copy_to_fablo[`copy_to_fablo`] script in link:{cc-pkg-dir}/[`{cc-pkg-dir}/`]
. Install the chaincode on the network peers (there is only one) by running `$ ./fabric-docker.sh chaincode install {cc-name}`
. Now you can try invoking the chaincode by issuing HTTP requests to the CLI container; for example, using `curl` (more details below)

// TODO update
///
.Invoking the chaincode
====
I am using https://httpie.io/[HTTPie], but you can also do this with `curl`.
Note that the command line outputs have been altered to make them more concise.

First, call the `/user/enroll` endpoint to get a bearer token (the default credentials are `admin/adminpw`):

----
$ http http://localhost:8801/user/enroll id=admin secret=adminpw
HTTP/1.1 200 OK

{
  "token": "ba945b10-0253-11ee-b51b-5b5e65097fa0-admin"
}
----

Then you can invoke the chaincode with the received token to try to run into a runtime assertion failure, like so:

----
$ http -v -A bearer -a ba945b10-0253-11ee-b51b-5b5e65097fa0-admin http://localhost:8801/invoke/my-channel1/notes method=CreateNote args:='["forbidden", "anything"]'
POST /invoke/my-channel1/notes HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Authorization: Bearer ba945b10-0253-11ee-b51b-5b5e65097fa0-admin
Content-Type: application/json

{ "args": ["forbidden", "anything"], "method": "CreateNote" }

HTTP/1.1 400 Bad Request

{ "message": "No valid responses from any peers. Errors:\n peer=peer0.org1.example.com:7041, status=500, message=Error during contract method execution" }
----
====
///
