= Dev Mode Test Network Configuration
2024-05-27
:toc:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:cc-name: tpcc

== USAGE

.Prerequisites
Make sure you have `docker` available (with `compose`, of course).
Note that `fablo` generates scripts that require the legacy `docker-compose` to exist in your `PATH`, so if you are using https://docs.docker.com/compose/migrate/[Compose V2], just place a wrapper binary (script) somewhere in your `PATH`.

.Instructions
. Normally, all you need to do is execute `$ ./fablo up` (or `$ ./fablo reset` if you have already ``up``’ed once)
** This should…
*** spin up a small local network with a single peer in a single organization (`org1`) and a single orderer (in a separate organization),
*** generate all crypto material automatically and transparently (you never need to see it),
*** create a channel named `my-channel1`,
*** install the chaincode definition (in dev mode) for `{cc-name}`,
*** and start some https://github.com/fablo-io/fablo-rest[Fablo REST] endpoints.
. Then you can proceed to try calling the chaincode as described below

.Invoking the chaincode
====
You should use the REST endpoints according to https://github.com/fablo-io/fablo-rest[Fablo REST’s] documentation.
That is, first generate a token using the credentials `admin/adminpw` at ``org1``’s REST API, then invoke the chaincode using that token and the appropriate parameterization.

I am using https://httpie.io/[HTTPie] and https://jqlang.github.io/jq/[`jq`], but you can also do this with `curl` and other command line / GUI tools.
Note that the command line outputs have been altered to make them more concise.

First, call the `/user/enroll` endpoint to get a bearer token (the default credentials are `admin/adminpw`) and save it in a variable `token`:

----
$ token=$(http http://localhost:8801/user/enroll id=admin secret=adminpw | jq .token | tr -d '"')
----

Then you can invoke the chaincode with the received token to invoke the chaincode, like so:

----
$ http -v -A bearer -a $token http://localhost:8801/invoke/my-channel1/tpcc method=initEntries args:='[]'
POST /invoke/my-channel1/notes HTTP/1.1
Accept: application/json, */*;q=0.5
Accept-Encoding: gzip, deflate
Authorization: Bearer ba945b10-0253-11ee-b51b-5b5e65097fa0-admin
Content-Type: application/json

{ "args": [], "method": "initEntries" }

HTTP/1.1 200 OK

{ "response": "" }
----
====
